# Generated by Django 3.1.6 on 2021-10-17 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(default='Null', max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Figures_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='media')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('original_title', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('paper_size', models.CharField(blank=True, max_length=50, null=True)),
                ('tracks', models.CharField(blank=True, max_length=50, null=True)),
                ('discs', models.CharField(blank=True, max_length=50, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('region_free', models.BooleanField(default=False, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('original_version', models.CharField(blank=True, max_length=50, null=True)),
                ('numbering', models.CharField(blank=True, max_length=50, null=True)),
                ('scale', models.IntegerField(blank=True, null=True)),
                ('no_of_parts', models.IntegerField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, max_length=1000, null=True)),
                ('nsfw', models.BooleanField(default=False)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('dimesnions', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.CharField(default='Null', max_length=50)),
                ('barcode', models.CharField(default='Null', max_length=50)),
                ('catalog', models.CharField(default='Null', max_length=50)),
                ('info', models.CharField(default='Null', max_length=1000)),
                ('run', models.CharField(default='Null', max_length=50)),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(default='Null', max_length=50)),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databases.figures_db')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databases.category')),
            ],
            options={
                'verbose_name': 'Sub-Category',
                'verbose_name_plural': 'Sub-Categories',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media')),
                ('figure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='databases.figures_db')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.AddField(
            model_name='figures_db',
            name='releases',
            field=models.ManyToManyField(to='databases.Releases'),
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Null', max_length=50)),
                ('name', models.CharField(default='Null', max_length=100)),
                ('original_name', models.CharField(default='Null', max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=50, null=True)),
                ('homepage', models.CharField(blank=True, default='Null', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('pg', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databases.figures_db')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
