# Generated by Django 3.1.6 on 2021-10-17 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='figure',
        ),
        migrations.CreateModel(
            name='Figures_entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databases.entries')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databases.figures_db')),
            ],
        ),
    ]
