# Generated by Django 3.1.6 on 2021-10-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_auto_20211018_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figures_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databases.category')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databases.figures_db')),
            ],
        ),
    ]
