# Generated by Django 3.1.6 on 2021-10-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_remove_subcategory_figure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figures_Releases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.CharField(default='Null', max_length=50)),
                ('barcode', models.CharField(default='Null', max_length=50)),
                ('catalog', models.CharField(default='Null', max_length=50)),
                ('info', models.CharField(default='Null', max_length=1000)),
                ('run', models.CharField(default='Null', max_length=50)),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.AlterModelOptions(
            name='figures_db',
            options={'verbose_name': 'Figure', 'verbose_name_plural': 'Figures'},
        ),
        migrations.RemoveField(
            model_name='figures_db',
            name='releases',
        ),
        migrations.AddField(
            model_name='figures_db',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='figures_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='databases.subcategory'),
        ),
        migrations.DeleteModel(
            name='Releases',
        ),
        migrations.AddField(
            model_name='figures_releases',
            name='figure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='databases.figures_db'),
        ),
    ]
