# Generated by Django 3.1.6 on 2021-10-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0005_auto_20211024_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figures_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.subcategory'),
        ),
        migrations.AlterField(
            model_name='figures_category',
            name='figure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.figures_db'),
        ),
        migrations.AlterField(
            model_name='figures_entries',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.entries'),
        ),
        migrations.AlterField(
            model_name='figures_entries',
            name='figure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.figures_db'),
        ),
        migrations.AlterField(
            model_name='figures_releases',
            name='figure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databases.figures_db'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='figure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databases.figures_db'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.category'),
        ),
    ]
