# Generated by Django 3.1.6 on 2021-10-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0007_auto_20211026_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='figures_db',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
