# Generated by Django 3.1.6 on 2021-10-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0008_figures_db_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='figures_category',
            options={'verbose_name': 'Figure Category'},
        ),
        migrations.AlterModelOptions(
            name='figures_entries',
            options={'verbose_name': 'Figure Entry'},
        ),
    ]
